spring:
  mail:
    default-encoding: UTF-8
    host: #your smtp server
    username: #your smtp server username
    password: #your smtp server password
    port: #your smtp port
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
    protocol: smtp
    test-connection: true
  datasource:
    hikari:
      username: #your database username
      password: #your database password
      auto-commit: off
      connection-test-query: #your connection test query
      validation-timeout: #your validation timeout
      minimum-idle: #your minimum idle
      maximum-pool-size: #your maximum pool size
      connection-timeout: #your connection timeout
    driver-class-name: #your driver class name
    url: #your database url
    sql-script-encoding: UTF-8
    platform: #your database platform ex) mariadb, mysql, oracle, mssql .....
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
